version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/chrkb1569/
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: ./BeforeInstall.sh
      timeout: 120
      runas: ubuntu

  ApplicationStart:
    - location: ./ApplicationStart.sh
      timeout: 120
      runas: ubuntu
