pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "https://github.com/chrkb1569/DevOps-Practice"
            }
        }

        stage('Build Project') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Docker Login') {
            steps {
                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t chrkb1569/jenkins:test .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push chrkb1569/jenkins:test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'ssh -o StrictHostKeyChecking=no ubuntu@$APPLICATION_SERVER'
                sh 'scp $JAR_FILE_PATH ubuntu@$APPLICATION_SERVER:/home/ubuntu/chrkb1569'
                sh 'scp $SCRIPT_FILE_PATH ubuntu@$APPLICATION_SERVER:/home/ubuntu/chrkb1569'
                sh 'ssh ubuntu@$APPLICATION_SERVER "sudo chmod 777 /home/ubuntu/chrkb1569/DockerDeploy.sh"'
                sh 'ssh ubuntu@$APPLICATION_SERVER "sudo chmod 777 /home/ubuntu/chrkb1569/*.jar"'
                sh 'ssh ubuntu@$APPLICATION_SERVER "/home/ubuntu/chrkb1569/DockerDeploy.sh"'
            }
        }
    }
}
